#!/usr/bin/env bash
#
# ssl.sh — SSL certificate management for UPOU AI HelpDesk
#
# Three actions in one script:
#   sudo ./ssl.sh setup       Obtain cert from Let's Encrypt + configure Apache HTTPS
#   sudo ./ssl.sh export      Backup certs + vhosts to a portable tar.gz
#   sudo ./ssl.sh import      Detect and restore a cert backup from common upload locations
#
# Run without arguments for usage help.

set -euo pipefail

# ========================================================================
# CONFIGURATION — edit these if your domains or ports change
# ========================================================================
DOMAINS=(
    "ai.upouhelp.tech"
    "ai.upouhelp.me"
    "upouaihelp.duckdns.org"
)

STUDENT_HTTP_PORT=80
STUDENT_HTTPS_PORT=443
ADMIN_HTTP_PORT=8080
ADMIN_HTTPS_PORT=8443

PROJECT_ROOT="/var/www/upou-helpdesk"
BACKUP_FILENAME="upou-ssl-backup.tar.gz"
# ========================================================================

PRIMARY_DOMAIN="${DOMAINS[0]}"
CERT_DIR="/etc/letsencrypt/live/$PRIMARY_DOMAIN"
TIMESTAMP=$(date +%Y%m%d-%H%M%S)

color_ok()    { printf "\033[32m✓\033[0m %s\n" "$1"; }
color_warn()  { printf "\033[33m!\033[0m %s\n" "$1"; }
color_err()   { printf "\033[31m✗\033[0m %s\n" "$1" >&2; }
color_phase() { printf "\n\033[1;34m=== %s ===\033[0m\n" "$1"; }

check_root() {
    if [[ $EUID -ne 0 ]]; then
        color_err "Run as root:  sudo $0 $1"
        exit 1
    fi
}

build_domain_flags() {
    local flags=""
    for d in "${DOMAINS[@]}"; do
        flags="$flags -d $d"
    done
    echo "$flags"
}

build_server_aliases() {
    local aliases=""
    for d in "${DOMAINS[@]:1}"; do
        aliases="${aliases}    ServerAlias $d"$'\n'
    done
    echo "$aliases"
}

install_prerequisites() {
    local need_install=0
    command -v certbot  >/dev/null 2>&1 || need_install=1
    command -v semanage >/dev/null 2>&1 || need_install=1
    httpd -M 2>/dev/null | grep -q ssl_module || need_install=1

    if [[ "$need_install" -eq 1 ]]; then
        echo "Installing certbot, mod_ssl, semanage..."
        dnf install -y certbot python3-certbot-apache mod_ssl policycoreutils-python-utils >/dev/null 2>&1
    fi
    color_ok "Prerequisites installed"
}

register_selinux_port() {
    local port=$1
    if semanage port -l 2>/dev/null | grep -qE "^http_port_t.*\b${port}\b"; then
        color_ok "SELinux: port $port already registered"
    else
        semanage port -a -t http_port_t -p tcp "$port" 2>/dev/null || \
        semanage port -m -t http_port_t -p tcp "$port" 2>/dev/null || true
        color_ok "SELinux: port $port registered"
    fi
}

setup_auto_renewal() {
    local cron_line="0 3 * * * certbot renew --quiet --post-hook 'systemctl reload httpd'"
    if ! crontab -l 2>/dev/null | grep -qF "certbot renew"; then
        (crontab -l 2>/dev/null || true; echo "$cron_line") | crontab -
        color_ok "Auto-renewal cron added (daily at 3am)"
    else
        color_ok "Auto-renewal cron already exists"
    fi
}

read_vhost_var() {
    local file=$1 var=$2
    grep -oP "SetEnv\s+${var}\s+\K\S+" "$file" 2>/dev/null || echo "MISSING"
}

write_student_ssl_vhost() {
    local db_pass s3_bucket aliases
    db_pass=$(read_vhost_var /etc/httpd/conf.d/upou-helpdesk.conf DB_PASS)
    s3_bucket=$(read_vhost_var /etc/httpd/conf.d/upou-helpdesk.conf S3_BUCKET)
    aliases=$(build_server_aliases)

    cat > /etc/httpd/conf.d/upou-helpdesk-ssl.conf << VEOF
# HTTPS — UPOU AI HelpDesk student app (port $STUDENT_HTTPS_PORT)
# Generated by ssl.sh on $(date)

<VirtualHost *:$STUDENT_HTTPS_PORT>
    ServerName $PRIMARY_DOMAIN
$aliases
    DocumentRoot $PROJECT_ROOT/php/public

    SSLEngine on
    SSLCertificateFile      $CERT_DIR/fullchain.pem
    SSLCertificateKeyFile   $CERT_DIR/privkey.pem

    <Directory $PROJECT_ROOT/php/public>
        Options -Indexes +FollowSymLinks
        AllowOverride All
        Require all granted
        DirectoryIndex index.php
    </Directory>

    SetEnv AWS_REGION             us-east-1
    SetEnv LAMBDA_FUNCTION_NAME   ai-webapp-handler
    SetEnv S3_BUCKET              $s3_bucket

    SetEnv DB_HOST     127.0.0.1
    SetEnv DB_PORT     3306
    SetEnv DB_NAME     upou_helpdesk
    SetEnv DB_USER     upou_app
    SetEnv DB_PASS     $db_pass

    SetEnv APP_DEBUG   false

    Header always set Strict-Transport-Security "max-age=63072000; includeSubDomains"
    Header always set X-Content-Type-Options "nosniff"
    Header always set X-Frame-Options "SAMEORIGIN"

    ErrorLog  /var/log/httpd/upou-helpdesk-ssl-error.log
    CustomLog /var/log/httpd/upou-helpdesk-ssl-access.log combined
</VirtualHost>
VEOF
    color_ok "Student HTTPS vhost → port $STUDENT_HTTPS_PORT"
}

write_admin_ssl_vhost() {
    local db_pass aliases
    db_pass=$(read_vhost_var /etc/httpd/conf.d/upou-admin.conf DB_PASS)
    aliases=$(build_server_aliases)

    cat > /etc/httpd/conf.d/upou-admin-ssl.conf << VEOF
# HTTPS — UPOU AI HelpDesk admin console (port $ADMIN_HTTPS_PORT)
# Generated by ssl.sh on $(date)

<VirtualHost *:$ADMIN_HTTPS_PORT>
    ServerName $PRIMARY_DOMAIN
$aliases
    DocumentRoot $PROJECT_ROOT/admin/public

    SSLEngine on
    SSLCertificateFile      $CERT_DIR/fullchain.pem
    SSLCertificateKeyFile   $CERT_DIR/privkey.pem

    <Directory $PROJECT_ROOT/admin/public>
        Options -Indexes +FollowSymLinks
        AllowOverride All
        Require all granted
        DirectoryIndex index.php
    </Directory>

    SetEnv AWS_REGION           us-east-1
    SetEnv DDB_TICKETS_TABLE    upou-helpdesk-tickets

    SetEnv DB_HOST     127.0.0.1
    SetEnv DB_PORT     3306
    SetEnv DB_NAME     upou_admin
    SetEnv DB_USER     upou_admin_app
    SetEnv DB_PASS     $db_pass

    SetEnv APP_DEBUG   false

    Header always set Strict-Transport-Security "max-age=63072000; includeSubDomains"
    Header always set X-Content-Type-Options "nosniff"
    Header always set X-Frame-Options "SAMEORIGIN"

    ErrorLog  /var/log/httpd/upou-admin-ssl-error.log
    CustomLog /var/log/httpd/upou-admin-ssl-access.log combined
</VirtualHost>
VEOF
    color_ok "Admin HTTPS vhost → port $ADMIN_HTTPS_PORT"
}

write_redirect_vhost() {
    local aliases
    aliases=$(build_server_aliases)

    cat > /etc/httpd/conf.d/upou-redirect.conf << VEOF
# HTTP → HTTPS redirects
# Generated by ssl.sh on $(date)

<VirtualHost *:$STUDENT_HTTP_PORT>
    ServerName $PRIMARY_DOMAIN
$aliases
    RewriteEngine On
    RewriteCond %{HTTPS} off
    RewriteRule ^(.*)$ https://%{HTTP_HOST}%{REQUEST_URI} [R=301,L]
</VirtualHost>

<VirtualHost *:$ADMIN_HTTP_PORT>
    ServerName $PRIMARY_DOMAIN
$aliases
    RewriteEngine On
    RewriteCond %{HTTPS} off
    RewriteRule ^(.*)$ https://%{HTTP_HOST}:${ADMIN_HTTPS_PORT}%{REQUEST_URI} [R=301,L]
</VirtualHost>
VEOF
    color_ok "HTTP→HTTPS redirect configured"
}

write_listen_directive() {
    if ! grep -rq "^Listen $ADMIN_HTTPS_PORT" /etc/httpd/conf*/ 2>/dev/null; then
        echo "Listen $ADMIN_HTTPS_PORT" > /etc/httpd/conf.d/listen-${ADMIN_HTTPS_PORT}.conf
        color_ok "Added Listen $ADMIN_HTTPS_PORT"
    else
        color_ok "Listen $ADMIN_HTTPS_PORT already exists"
    fi
}

restart_apache() {
    if ! apachectl configtest 2>&1 | grep -q "Syntax OK"; then
        color_err "Apache config test FAILED:"
        apachectl configtest
        exit 1
    fi
    color_ok "Apache config syntax OK"

    systemctl restart httpd
    sleep 2

    if ! systemctl is-active httpd >/dev/null; then
        color_err "Apache failed to start"
        journalctl -u httpd -n 20 --no-pager
        exit 1
    fi
    color_ok "Apache restarted"
}

verify_https() {
    color_phase "Verification"

    for port in "$STUDENT_HTTPS_PORT" "$ADMIN_HTTPS_PORT"; do
        if ss -tlnp | grep -q ":${port}\b"; then
            color_ok "Port $port is listening"
        else
            color_err "Port $port is NOT listening"
        fi
    done

    for d in "${DOMAINS[@]}"; do
        local code
        code=$(curl -sk -o /dev/null -w "%{http_code}" "https://${d}/" 2>/dev/null || echo "fail")
        if [[ "$code" == "200" || "$code" == "302" ]]; then
            color_ok "https://$d/ → HTTP $code"
        else
            color_warn "https://$d/ → HTTP $code (DNS propagation or SG needed)"
        fi
    done

    local admin_code
    admin_code=$(curl -sk -o /dev/null -w "%{http_code}" "https://${PRIMARY_DOMAIN}:${ADMIN_HTTPS_PORT}/" 2>/dev/null || echo "fail")
    if [[ "$admin_code" == "200" || "$admin_code" == "302" ]]; then
        color_ok "https://${PRIMARY_DOMAIN}:${ADMIN_HTTPS_PORT}/ → HTTP $admin_code"
    else
        color_warn "https://${PRIMARY_DOMAIN}:${ADMIN_HTTPS_PORT}/ → HTTP $admin_code"
    fi

    local redirect_code
    redirect_code=$(curl -sk -o /dev/null -w "%{http_code}" "http://${PRIMARY_DOMAIN}/" 2>/dev/null || echo "fail")
    if [[ "$redirect_code" == "301" ]]; then
        color_ok "http://${PRIMARY_DOMAIN}/ → 301 redirect to HTTPS"
    else
        color_warn "http://${PRIMARY_DOMAIN}/ → HTTP $redirect_code (expected 301)"
    fi
}

print_summary() {
    local expiry
    expiry=$(openssl x509 -enddate -noout -in "$CERT_DIR/fullchain.pem" 2>/dev/null | cut -d= -f2 || echo "check manually")

    cat << EOF

SSL is active. Your endpoints:

  Student app:
    https://${DOMAINS[0]}/
    https://${DOMAINS[1]}/
    https://${DOMAINS[2]}/

  Admin console:
    https://${DOMAINS[0]}:${ADMIN_HTTPS_PORT}/
    https://${DOMAINS[1]}:${ADMIN_HTTPS_PORT}/
    https://${DOMAINS[2]}:${ADMIN_HTTPS_PORT}/

  Certificate:
    Location:  $CERT_DIR/
    Expires:   $expiry
    Renewal:   automatic via cron (daily at 3am)

  Security group reminder:
    TCP $STUDENT_HTTPS_PORT   from 0.0.0.0/0    (student HTTPS)
    TCP $ADMIN_HTTPS_PORT  from My IP        (admin HTTPS)

EOF
}


# ########################################################################
#                            ACTION: SETUP
# ########################################################################
do_setup() {
    check_root "setup"

    color_phase "SSL Setup — UPOU AI HelpDesk"
    echo "Domains: ${DOMAINS[*]}"
    echo "Student: port $STUDENT_HTTPS_PORT  |  Admin: port $ADMIN_HTTPS_PORT"

    # 1. Prerequisites
    color_phase "1. Prerequisites"
    install_prerequisites

    # 2. DNS check
    color_phase "2. DNS verification"
    local public_ip all_ok=1
    public_ip=$(curl -s http://169.254.169.254/latest/meta-data/public-ipv4 2>/dev/null || echo "unknown")
    echo "EC2 public IP: $public_ip"

    for d in "${DOMAINS[@]}"; do
        local resolved
        resolved=$(dig +short "$d" 2>/dev/null | head -1)
        if [[ "$resolved" == "$public_ip" ]]; then
            color_ok "$d → $resolved"
        else
            color_warn "$d → ${resolved:-NXDOMAIN} (expected $public_ip)"
            all_ok=0
        fi
    done

    if [[ "$all_ok" -eq 0 ]]; then
        echo ""
        color_warn "Some domains don't resolve to this EC2 yet."
        echo "Certbot will fail if it can't reach this server via the domain."
        echo ""
        echo "Options:"
        echo "  1. Fix DNS and re-run this script"
        echo "  2. Press Enter to continue anyway (certbot may fail)"
        echo "  3. Ctrl+C to abort"
        read -r
    fi

    # 3. SELinux
    color_phase "3. SELinux"
    register_selinux_port "$ADMIN_HTTPS_PORT"

    # 4. Obtain certificate
    color_phase "4. Obtaining certificate"
    if [[ -d "$CERT_DIR" ]]; then
        local expiry
        expiry=$(openssl x509 -enddate -noout -in "$CERT_DIR/fullchain.pem" 2>/dev/null | cut -d= -f2)
        color_ok "Certificate already exists (expires: $expiry)"
        echo "To force re-issue: sudo certbot certonly --apache $(build_domain_flags) --force-renewal"
    else
        local email_flag
        if [[ -n "${CERT_EMAIL:-}" ]]; then
            email_flag="-m $CERT_EMAIL"
        else
            email_flag="--register-unsafely-without-email"
            color_warn "No CERT_EMAIL set; won't receive expiry warnings"
            color_warn "Set it with: export CERT_EMAIL='you@example.com' before running"
        fi

        certbot certonly \
            --apache \
            $(build_domain_flags) \
            $email_flag \
            --agree-tos \
            --non-interactive

        if [[ -d "$CERT_DIR" ]]; then
            color_ok "Certificate obtained for: ${DOMAINS[*]}"
        else
            color_err "Certbot failed. Check the output above."
            exit 1
        fi
    fi

    # 5. HTTPS vhosts
    color_phase "5. HTTPS vhosts"
    write_student_ssl_vhost
    write_admin_ssl_vhost
    write_redirect_vhost
    write_listen_directive

    # 6. Restart
    color_phase "6. Restarting Apache"
    restart_apache

    # 7. Verify
    verify_https

    # 8. Auto-renewal
    color_phase "8. Auto-renewal"
    setup_auto_renewal

    # Done
    color_phase "Setup Complete"
    print_summary
}


# ########################################################################
#                            ACTION: EXPORT
# ########################################################################
do_export() {
    check_root "export"

    color_phase "Exporting SSL certificates"

    if [[ ! -d /etc/letsencrypt/live ]]; then
        color_err "No certificates found. Run '$0 setup' first."
        exit 1
    fi

    # Show what we have
    echo "Certificates:"
    for d in /etc/letsencrypt/live/*/; do
        local name expiry
        name=$(basename "$d")
        [[ "$name" == "README" ]] && continue
        if [[ -f "$d/fullchain.pem" ]]; then
            expiry=$(openssl x509 -enddate -noout -in "$d/fullchain.pem" 2>/dev/null | cut -d= -f2)
            echo "  $name → expires $expiry"
        fi
    done
    echo ""

    # Collect SSL-related Apache configs
    local ssl_configs=""
    for f in /etc/httpd/conf.d/*ssl*.conf \
             /etc/httpd/conf.d/*redirect*.conf \
             /etc/httpd/conf.d/listen-*.conf; do
        [[ -f "$f" ]] && ssl_configs="$ssl_configs $f"
    done

    # Build the tarball
    local backup_path="/tmp/$BACKUP_FILENAME"
    tar czf "$backup_path" \
        /etc/letsencrypt/ \
        $ssl_configs \
        2>/dev/null

    local size
    size=$(du -h "$backup_path" | cut -f1)

    # Copy to ec2-user home for easy download
    local easy_path="/home/ec2-user/$BACKUP_FILENAME"
    cp "$backup_path" "$easy_path"
    chown ec2-user:ec2-user "$easy_path"

    color_ok "Backup created: $easy_path ($size)"

    cat << EOF

Download to your laptop:

  scp -i ~/Downloads/upou-helpdesk-key.pem \\
    ec2-user@<THIS_EC2_IP>:~/$BACKUP_FILENAME \\
    ~/Downloads/

To restore on a new EC2, upload the file then run:

  sudo $0 import

The import command auto-detects the backup file from common locations.

EOF
}


# ########################################################################
#                            ACTION: IMPORT
# ########################################################################
do_import() {
    check_root "import"

    color_phase "Importing SSL certificates"

    # ---- 1. Find the backup file ----
    color_phase "1. Locating backup file"

    local backup_file=""
    local search_paths=(
        "/tmp/$BACKUP_FILENAME"
        "/home/ec2-user/$BACKUP_FILENAME"
        "/root/$BACKUP_FILENAME"
        "/mnt/user-data/uploads/$BACKUP_FILENAME"
        "/home/ec2-user/upou-ssl-backup-*.tar.gz"
        "/tmp/upou-ssl-backup*.tar.gz"
    )

    # Also accept an explicit path as argument
    if [[ -n "${2:-}" && -f "${2:-}" ]]; then
        backup_file="$2"
        color_ok "Using specified file: $backup_file"
    else
        echo "Searching for backup in common locations..."
        for pattern in "${search_paths[@]}"; do
            # Use ls to expand globs
            for f in $pattern; do
                if [[ -f "$f" ]]; then
                    backup_file="$f"
                    break 2
                fi
            done
        done
    fi

    if [[ -z "$backup_file" ]]; then
        color_err "No backup file found!"
        echo ""
        echo "Upload the backup to the EC2 instance first:"
        echo ""
        echo "  scp -i ~/Downloads/upou-helpdesk-key.pem \\"
        echo "    ~/Downloads/$BACKUP_FILENAME \\"
        echo "    ec2-user@<EC2_IP>:/tmp/"
        echo ""
        echo "Then re-run:  sudo $0 import"
        echo ""
        echo "Or specify the path directly:"
        echo "  sudo $0 import /path/to/$BACKUP_FILENAME"
        echo ""
        echo "Searched locations:"
        for p in "${search_paths[@]}"; do
            echo "  $p"
        done
        exit 1
    fi

    color_ok "Found backup: $backup_file"
    local size
    size=$(du -h "$backup_file" | cut -f1)
    echo "  Size: $size"

    # Peek inside to verify it's a valid backup
    if ! tar tzf "$backup_file" 2>/dev/null | grep -q "letsencrypt"; then
        color_err "File doesn't look like a valid SSL backup (no letsencrypt/ inside)"
        exit 1
    fi
    color_ok "Backup contents verified"

    # ---- 2. Install prerequisites ----
    color_phase "2. Prerequisites"
    install_prerequisites

    # ---- 3. Stop Apache during restore ----
    systemctl stop httpd 2>/dev/null || true

    # ---- 4. Backup existing certs if any ----
    if [[ -d /etc/letsencrypt ]]; then
        local old_backup="/tmp/letsencrypt-previous-$TIMESTAMP"
        mv /etc/letsencrypt "$old_backup"
        color_ok "Existing /etc/letsencrypt moved to $old_backup"
    fi

    # ---- 5. Extract ----
    color_phase "3. Extracting certificates"
    cd /
    tar xzf "$backup_file"
    color_ok "Extracted"

    # ---- 6. Verify certs ----
    color_phase "4. Verifying certificates"
    local cert_count=0
    for d in /etc/letsencrypt/live/*/; do
        local name
        name=$(basename "$d")
        [[ "$name" == "README" ]] && continue
        if [[ -f "$d/fullchain.pem" && -f "$d/privkey.pem" ]]; then
            local expiry
            expiry=$(openssl x509 -enddate -noout -in "$d/fullchain.pem" 2>/dev/null | cut -d= -f2)
            color_ok "$name (expires: $expiry)"
            cert_count=$((cert_count + 1))
        fi
    done

    if [[ "$cert_count" -eq 0 ]]; then
        color_err "No valid certificates found in backup"
        exit 1
    fi

    # Fix permissions
    chmod -R 700 /etc/letsencrypt/archive/ 2>/dev/null || true
    chmod -R 700 /etc/letsencrypt/live/ 2>/dev/null || true

    # ---- 7. Fix vhost paths ----
    color_phase "5. Fixing vhost configurations"

    for conf in /etc/httpd/conf.d/*ssl*.conf; do
        [[ -f "$conf" ]] || continue
        # Fix DocumentRoot paths to match current project location
        sed -i "s|DocumentRoot .*/php/public|DocumentRoot $PROJECT_ROOT/php/public|g" "$conf"
        sed -i "s|<Directory .*/php/public>|<Directory $PROJECT_ROOT/php/public>|g" "$conf"
        sed -i "s|DocumentRoot .*/admin/public|DocumentRoot $PROJECT_ROOT/admin/public|g" "$conf"
        sed -i "s|<Directory .*/admin/public>|<Directory $PROJECT_ROOT/admin/public>|g" "$conf"
        color_ok "Fixed paths in $(basename "$conf")"
    done

    # Sync DB passwords from HTTP vhosts to SSL vhosts
    for pair in "upou-helpdesk.conf:upou-helpdesk-ssl.conf" "upou-admin.conf:upou-admin-ssl.conf"; do
        local http_vhost="/etc/httpd/conf.d/${pair%%:*}"
        local ssl_vhost="/etc/httpd/conf.d/${pair##*:}"
        if [[ -f "$http_vhost" && -f "$ssl_vhost" ]]; then
            local current_pass
            current_pass=$(read_vhost_var "$http_vhost" DB_PASS)
            if [[ -n "$current_pass" && "$current_pass" != "MISSING" ]]; then
                sed -i "s|SetEnv DB_PASS .*|SetEnv DB_PASS     $current_pass|" "$ssl_vhost"
                color_ok "Synced DB_PASS: $(basename "$http_vhost") → $(basename "$ssl_vhost")"
            fi
        fi
    done

    # ---- 8. SELinux ----
    color_phase "6. SELinux"
    register_selinux_port "$ADMIN_HTTPS_PORT"

    # ---- 9. Listen directive ----
    write_listen_directive

    # ---- 10. Start Apache ----
    color_phase "7. Starting Apache"
    restart_apache

    # ---- 11. Verify ----
    verify_https

    # ---- 12. Auto-renewal ----
    setup_auto_renewal

    # ---- Done ----
    local public_ip
    public_ip=$(curl -s http://169.254.169.254/latest/meta-data/public-ipv4 2>/dev/null || echo "<check manually>")

    color_phase "Import Complete"

    cat << EOF

Certificates restored and Apache is running with SSL.

This EC2's public IP: $public_ip

Required steps:

  1. Update DNS A records to point to $public_ip:
     - ai.upouhelp.tech  → $public_ip
     - ai.upouhelp.me    → $public_ip
     - DuckDNS:
       curl "https://www.duckdns.org/update?domains=upouaihelp&token=YOUR_TOKEN&ip="

  2. Update EC2 security group inbound rules:
     TCP $STUDENT_HTTPS_PORT   from 0.0.0.0/0
     TCP $ADMIN_HTTPS_PORT  from My IP

  3. Test:
     curl -sk https://ai.upouhelp.tech/
     curl -sk https://ai.upouhelp.me:$ADMIN_HTTPS_PORT/

EOF
    print_summary
}


# ########################################################################
#                               MAIN
# ########################################################################
ACTION="${1:-help}"

case "$ACTION" in
    setup)
        do_setup
        ;;
    export)
        do_export
        ;;
    import)
        do_import "$@"
        ;;
    *)
        cat << EOF
UPOU AI HelpDesk — SSL Certificate Management

Usage:
  sudo $0 setup                  Obtain Let's Encrypt cert + configure HTTPS
  sudo $0 export                 Backup certs to ~/$BACKUP_FILENAME
  sudo $0 import [file]          Restore certs on a new EC2 instance

Configured domains:
$(for d in "${DOMAINS[@]}"; do echo "  - $d"; done)

Ports:
  Student app:   $STUDENT_HTTP_PORT (HTTP) → $STUDENT_HTTPS_PORT (HTTPS)
  Admin console: $ADMIN_HTTP_PORT (HTTP) → $ADMIN_HTTPS_PORT (HTTPS)

Workflow for Learner Lab session rotation:

  OLD EC2 (before session expires):
    sudo ./ssl.sh export
    scp ec2-user@OLD_IP:~/$BACKUP_FILENAME ~/Downloads/

  NEW EC2 (after fresh launch):
    scp ~/Downloads/$BACKUP_FILENAME ec2-user@NEW_IP:/tmp/
    sudo ./ssl.sh import
    # Update DNS A records to the new IP
    # Update security group rules

EOF
        ;;
esac
